from config import WIDTH, HEIGHT
# define view GAME

GAP = 3
OFFSET = 25
W_SQUARE = 35
H_SQUARE = 35
R_SQUARE = 6

Y_LEFT_MENU = 25
W_LEFT_MENU = int(WIDTH / 256 * 85)
X_LEFT_MENU = WIDTH - Y_LEFT_MENU - W_LEFT_MENU
H_LEFT_MENU = HEIGHT - Y_LEFT_MENU - Y_LEFT_MENU
R_LEFT_MENU = 23

X_3COLORS = X_LEFT_MENU + 20
Y_3COLORS = Y_LEFT_MENU + 20

W_MISS = 15
H_MISS = 42
R_MISS = 6


R_BUTTON = 20